table C1
	lineageTag: f7d378fe-32ff-42ec-a845-668d7181ba09

	measure 'Sum Transaction' = sum('Transaction'[amount])
		lineageTag: 3054681d-62b3-475b-844a-4060b638f5fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column C1
		dataType: int64
		formatString: 0
		lineageTag: 18a76219-b460-4e6f-91b9-9c94f084854a
		summarizeBy: none
		sourceColumn: C1

		annotation SummarizationSetBy = Automatic

	column Libellé_Court
		dataType: string
		lineageTag: a7911f18-dc03-4a6f-96b2-a525aa1fef91
		summarizeBy: none
		sourceColumn: Libellé_Court

		annotation SummarizationSetBy = Automatic

	column C1_Lib_Court
		dataType: string
		lineageTag: b45f39a8-530a-4d47-9ad1-6a86d39d7e44
		summarizeBy: none
		sourceColumn: C1_Lib_Court

		annotation SummarizationSetBy = Automatic

	partition C1 = m
		mode: import
		queryGroup: 'model tables'
		source = ```
				let
				    Source = Sql.Databases("mhirzqqnk57e7anmxqvc3cldyq-ad6po2r4ekrefdnhlqka77jyjq.datawarehouse.fabric.microsoft.com"),
				    Dim_1 = Source{[Name="Magasin_table"]}[Data],
				    Query = "
				        SELECT *
				        FROM dbo.c1
				    ",
				    NativeQuery = Value.NativeQuery(Dim_1, Query)
				in 
				    NativeQuery
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

