table 'Dynamic Logo'
	lineageTag: 0fa64fcd-f9eb-4874-a217-192713be8485

	measure DynLogoHtml = "<div style='text-align:center'><img src='"&FIRSTNONBLANK('Dynamic Logo'[Logo],'Dynamic Logo'[Logo])&"' style='height:100vh'></div>"
		lineageTag: ecdd69d9-5cfe-4610-90a7-f46eff0c3aec

	column id
		dataType: string
		lineageTag: bd0abca6-5491-4b7f-a20a-d2718c97c74e
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column Logo
		dataType: string
		lineageTag: e1d6d353-d6de-43d1-a1f4-b75de458042e
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Logo

		annotation SummarizationSetBy = Automatic

	partition 'Dynamic Logo' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("NHvXlqvKku2/nFfOabzr+4QTwhvhe/QDCO8RVnz9TdUevfZYtap2ISAzIqbJjPyf", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [id = _t, Logo = _t]),
				    #"Type modifié" = Table.TransformColumnTypes(Source,{{"id", type text}, {"Logo", type text}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

