table Mesures
	lineageTag: b17bd7e4-d902-4751-a383-43c863447c06

	measure 'Capitaux Propres' =
			
			CALCULATE(
			    [Soldes],
			    FILTER(
			        'Dim_Ledger Accounts',
			        LEFT('Dim_Ledger Accounts'[number], 3) IN {
			            "101", "102", "103", "104", "105", "106",
			            "110", "111", "112", "113", "114", "115", "116", "117", "118", "119"
			        }
			    )
			)
		formatString: #,0
		displayFolder: Comptabilité
		lineageTag: 5247595d-ae4c-46e0-b3a2-b81149a1028a

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Dettes Financières' =
			
			CALCULATE(
			    [Soldes],
			    FILTER(
			        'Dim_Ledger Accounts',
			        LEFT('Dim_Ledger Accounts'[number], 2) = "16" &&
			        NOT LEFT('Dim_Ledger Accounts'[number], 4) = "1688"
			    )
			)
		displayFolder: Comptabilité
		lineageTag: d3027ceb-144b-48f9-a1b6-0c7cc0d143a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Trésorerie = ```
			
			VAR _CompanyID = SELECTEDVALUE(Dim_Companies[id])
			
			VAR _DateDebut = 
			    SWITCH(
			        TRUE(),
			        _CompanyID = "21912624", DATE(2024, 10, 1),
			        _CompanyID = "22276641", DATE(2024, 4, 1),
			        DATE(2025, 1, 1)
			    )
			
			VAR _Resultat = 
			    CALCULATE(
			        [Solde],
			        ALL(Dim_Date),
			        FILTER(Dim_Date, 'Dim_Date'[Date] >= _DateDebut),
			        FILTER('Dim_Ledger Accounts', 'Dim_Ledger Accounts'[C3] = "512")
			    )
			
			RETURN
			    IF(
			        NOT ISBLANK(_CompanyID),
			        _Resultat,
			        BLANK()
			    )
			
			```
		formatString: 0
		displayFolder: Comptabilité\tresorerie
		lineageTag: e9ac0c6c-7df6-4952-8d84-e5f31552113c

	measure 'Endettement Financier Net' =
			
			[Dettes Financières] - [Trésorerie]
		displayFolder: Comptabilité
		lineageTag: 6ab34653-91c7-4942-90dc-338f0095e7ef

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ratio Endettement' =
			
			DIVIDE(
			    [Endettement Financier Net],
			    [Capitaux Propres]
			)
		formatString: #,0\ %;-#,0\ %;#,0\ %
		displayFolder: Comptabilité
		lineageTag: ff97a871-8229-4ea4-b890-1fa8f04950c0

	measure 'Total Actif' =
			
			CALCULATE(
			    [Soldes],
			    FILTER(
			        'Dim_Ledger Accounts',
			        LEFT('Dim_Ledger Accounts'[number], 1) IN {"2", "3", "4", "5"}
			    )
			)
		displayFolder: Comptabilité
		lineageTag: 1ccd0abe-e7d4-4e4b-bab9-9d5cc8fefc65

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Passif' =
			
			CALCULATE(
			    [Soldes],
			    FILTER(
			        'Dim_Ledger Accounts',
			        LEFT('Dim_Ledger Accounts'[number], 1) IN {"1", "2", "4", "5"}
			    )
			)
		displayFolder: Comptabilité
		lineageTag: 77d0d442-e719-4e5c-9c7c-4aea9f718942

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ratio de Solvabilité' =
			
			DIVIDE(
			    [Capitaux Propres],
			    [Total Passif]
			)
		formatString: #,0\ %;-#,0\ %;#,0\ %
		displayFolder: Comptabilité
		lineageTag: 25d4fa5e-6a4b-4810-aeab-5f4e7f94df01

	measure 'Autonomie Financière' =
			
			DIVIDE(
			    [Capitaux Propres],
			    [Total Actif]
			)
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: Comptabilité
		lineageTag: ef30962a-f4ad-4d6b-8cfc-4688d5b2b0a8

	measure Soldes = -CALCULATE(SUM(Fact_GL[debit])-SUM(Fact_GL[credit]))
		displayFolder: Comptabilité
		lineageTag: eb861d62-8bd2-43ee-a62c-74b16d582d5c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Ventes' =
			
			CALCULATE(
			    [Soldes],
			    FILTER(
			        'Dim_Ledger Accounts',
			        'Dim_Ledger Accounts'[IsVente] = 1
			    )
			)
		formatString: #,0
		displayFolder: Ventes
		lineageTag: 7bb180f0-3372-4661-8188-ddea7cd9432d

	measure 'Nombre Factures' =
			
			CALCULATE(
			    DISTINCTCOUNT(Fact_GL[id_ledger_entry_lines]),
			    'Dim_Ledger Accounts'[IsVente] = 1
			)
		formatString: #,0
		displayFolder: Ventes
		lineageTag: 64df0ab0-e1e2-4228-ad70-13766b73b287

	measure 'Ventes Mois' =
			
			CALCULATE(
			    [Total Ventes],
			    DATESMTD('Dim_Date'[Date])
			)
		formatString: #,0
		displayFolder: Ventes
		lineageTag: 91d50c94-4758-4beb-bd76-6e006428e9ba

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Ventes Mois Précédent' =
			
			CALCULATE(
			    [Total Ventes],
			    PREVIOUSMONTH(Dim_Date[Date])
			)
		formatString: #,0
		displayFolder: Ventes
		lineageTag: c608996b-d627-4ab2-b340-6253d284da79

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Coût Total' =
			
			CALCULATE(
			    [Solde],
			    FILTER(
			        'Dim_Ledger Accounts',
			        'Dim_Ledger Accounts'[IsAchat] = 1
			    )
			)
		displayFolder: Ventes
		lineageTag: 8d250f6e-62e4-42f1-9ef2-7e511599cf1d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Marge Brute' =
			
			[Total Ventes] - [Coût Total]
		formatString: #,0
		displayFolder: Ventes
		lineageTag: 30eb5cdb-7dc0-4842-8033-867e59425275

	measure 'MoM % Revenus' = ```
			
			VAR Revenus_Courant = [Total Ventes]
			VAR Revenus_Mois_Prec = 
			    CALCULATE(
			        [Total Ventes],
			        DATEADD('Dim_Date'[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(Revenus_Courant - Revenus_Mois_Prec, Revenus_Mois_Prec, 0)
			```
		displayFolder: Ventes
		lineageTag: f32d570d-738e-488e-8cdc-301feda0a9ab

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue Avg Mo' =
			
			FORMAT(
			    AVERAGEX(
			        ADDCOLUMNS(
			            VALUES('Dim_Date'[Mois]),
			            "Revenue", [Total Ventes]
			        ),
			        [Revenue]
			    ),
			    "€#,##0,.0K" & " avg/mo"
			)
		displayFolder: Ventes
		lineageTag: 12ef7f84-e192-410d-acc5-babe5353cda9

	measure 'Revenue MoM % Text' = ```
			
			VAR _MoM = [MoM % Revenus]
			VAR _Result =
			    SWITCH(
			        TRUE(),
			        ISBLANK(_MoM), "",
			        _MoM < 0, "▼ " & FORMAT(_MoM, "0.0%"), 
			        _MoM >= 0, "▲ " & FORMAT(_MoM, "0.0%")
			    )
			RETURN
			    _Result
			```
		displayFolder: Ventes
		lineageTag: a1971613-1594-482c-a8d5-39ece53ef5bc

	measure 'Revenue MoM Libellé FR' = ```
			
			VAR _DernierMoisVisible = MAX('Dim_Date'[Mois])
			VAR _DebutMois = 
			    CALCULATE(
			        MIN('Dim_Date'[Date]),
			        Dim_Date[Mois] = _DernierMoisVisible
			    )
			
			VAR _MoisCompletActuel =
			    CALCULATE(
			        MAX('Dim_Date'[Date]),
			        REMOVEFILTERS('Dim_Date'),
			        DATESBETWEEN(
			            'Dim_Date'[Date],
			            EOMONTH(_DebutMois, -2) + 1,
			            EOMONTH(_DebutMois, -1)
			        )
			    )
			
			VAR _MoisCompletPrecedent =
			    CALCULATE(
			        MAX(Dim_Date[Date]),
			        REMOVEFILTERS(Dim_Date),
			        DATESBETWEEN(
			            Dim_Date[Date],
			            EOMONTH(_DebutMois, -3) + 1,
			            EOMONTH(_DebutMois, -2)
			        )
			    )
			
			VAR _Resultat = 
			    FORMAT(_MoisCompletActuel, "[$-fr-FR]mmmm yy") & 
			    " vs " & 
			    FORMAT(_MoisCompletPrecedent, "[$-fr-FR]mmmm yy")
			
			RETURN
			    SUBSTITUTE(_Resultat, "20", "")
			
			```
		displayFolder: Ventes
		lineageTag: 508edecc-a62b-4694-81d1-4dad5d6a72a0

	measure 'Marge Brut Avg Mo' =
			
			FORMAT(
			    AVERAGEX(
			        ADDCOLUMNS(
			            VALUES('Dim_Date'[Mois]),
			            "Marge Brut", [Marge Brute]
			        ),
			        [Marge Brut]
			    ),
			    "€#,##0,.0K" & " avg/mo"
			)
		displayFolder: Ventes
		lineageTag: 855e3609-9d8e-4f24-861c-d3385993e1b0

	measure 'MoM % Marge' = ```
			
			VAR Marge_Courant = [Marge Brute]
			VAR Marge_Mois_Prec = 
			    CALCULATE(
			        [Marge Brute],
			        DATEADD('Dim_Date'[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(Marge_Courant - Marge_Mois_Prec, Marge_Mois_Prec, 0)
			```
		displayFolder: Ventes
		lineageTag: 78b037df-0f1e-4743-944d-ea9bcabca612

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Marge MoM % Text' = ```
			
			VAR _MoM = [MoM % Marge]
			VAR _Result =
			    SWITCH(
			        TRUE(),
			        ISBLANK(_MoM), "",
			        _MoM < 0, "▼ " & FORMAT(_MoM, "0.0%"), 
			        _MoM >= 0, "▲ " & FORMAT(_MoM, "0.0%")
			    )
			RETURN
			    _Result
			```
		displayFolder: Ventes
		lineageTag: 9732c294-99aa-43f4-ac1f-31996bbfc22e

	measure 'MoM % CP' = ```
			
			VAR Revenus_Courant = [Capitaux Propres]
			VAR Revenus_Mois_Prec = 
			    CALCULATE(
			        [Capitaux Propres],
			        DATEADD('Dim_Date'[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(Revenus_Courant - Revenus_Mois_Prec, Revenus_Mois_Prec, 0)
			```
		displayFolder: Comptabilité
		lineageTag: 941ab62c-f8dc-4c25-b8fc-ce4c66f3c2de

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CP MoM % Text' = ```
			
			VAR _MoM = [MoM % CP]
			VAR _Result =
			    SWITCH(
			        TRUE(),
			        ISBLANK(_MoM), "",
			        _MoM < 0, "▼ " & FORMAT(_MoM, "0.0%"), 
			        _MoM >= 0, "▲ " & FORMAT(_MoM, "0.0%")
			    )
			RETURN
			    _Result
			```
		displayFolder: Comptabilité
		lineageTag: f9c14240-2ff4-4430-89d0-0992b4c3611a

	measure 'CP Avg Mo' =
			
			FORMAT(
			    AVERAGEX(
			        ADDCOLUMNS(
			            VALUES('Dim_Date'[Mois]),
			            "Capitaux Propres", [Capitaux Propres]
			        ),
			        [Capitaux Propres]
			    ),
			    "€#,##0,.0K" & " avg/mo"
			)
		displayFolder: Comptabilité
		lineageTag: 999dd723-64ba-4966-a823-0c96dfa5b03b

	measure 'MoM % EFN' = ```
			
			VAR EFN_Courant = [Endettement Financier Net]
			VAR EFN_Mois_Prec = 
			    CALCULATE(
			        [Endettement Financier Net],
			        DATEADD('Dim_Date'[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(EFN_Courant - EFN_Mois_Prec, EFN_Mois_Prec, 0)
			```
		displayFolder: Comptabilité
		lineageTag: e308e6ff-052c-4dc7-abe5-9c0ac360926e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'EFN MoM % Text' = ```
			
			VAR _MoM = [MoM % EFN]
			VAR _Result =
			    SWITCH(
			        TRUE(),
			        ISBLANK(_MoM), "",
			        _MoM < 0, "▼ " & FORMAT(_MoM, "0.0%"), 
			        _MoM >= 0, "▲ " & FORMAT(_MoM, "0.0%")
			    )
			RETURN
			    _Result
			```
		displayFolder: Comptabilité
		lineageTag: 09e6da1f-1fab-41df-bf33-9f861a101c85

	measure 'EFN Avg Mo' =
			
			FORMAT(
			    AVERAGEX(
			        ADDCOLUMNS(
			            VALUES('Dim_Date'[Mois]),
			            "Endettement Financier Net", [Endettement Financier Net]
			        ),
			        [Endettement Financier Net]
			    ),
			    "€#,##0,.0K" & " avg/mo"
			)
		displayFolder: Comptabilité
		lineageTag: fc5b41ac-663f-455a-991d-e8b95f1e0005

	measure 'Facture Impayées' = CALCULATE(SUM('Customer invoices'[amount]),'Customer invoices'[status]="late",USERELATIONSHIP(Dim_Date[Date],'Customer invoices'[date]))
		formatString: 0
		displayFolder: Ventes
		lineageTag: 9c034085-56d1-4885-be4e-9aaf5a5e1aa8

	measure 'MoM % FI' = ```
			
			VAR Marge_Courant = [Facture Impayées]
			VAR Marge_Mois_Prec = 
			    CALCULATE(
			        [Facture Impayées],
			        DATEADD(Dim_Date[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(Marge_Courant - Marge_Mois_Prec, Marge_Mois_Prec, 0)
			```
		displayFolder: Ventes
		lineageTag: a7e16473-7e5d-440f-a0a1-9e9e431b7c17

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FI MoM % Text' = ```
			
			VAR _MoM = [MoM % FI]
			VAR _Result =
			    SWITCH(
			        TRUE(),
			        ISBLANK(_MoM), "",
			        _MoM < 0, "▼ " & FORMAT(_MoM, "0.0%"), 
			        _MoM >= 0, "▲ " & FORMAT(_MoM, "0.0%")
			    )
			RETURN
			    _Result
			```
		displayFolder: Ventes
		lineageTag: 2d240553-e5a5-4a14-a830-14122e45e057

	measure 'FI Avg Mo' =
			
			FORMAT(
			    AVERAGEX(
			        ADDCOLUMNS(
			            VALUES('Dim_Date'[Mois]),
			            "Facture Impayées", [Facture Impayées]
			        ),
			        [Facture Impayées]
			    ),
			    "€#,##0,.0K" & " avg/mo"
			)
		displayFolder: Ventes
		lineageTag: 85792436-0ec6-4d23-a33d-287455d3dac6

	measure 'Résultat Opérationnel' =
			
			CALCULATE(
			    [Soldes],
			    FILTER(
			        'Dim_Ledger Accounts',
			        LEFT('Dim_Ledger Accounts'[Compte], 1) IN {
			            "7",
			            "6"
			        }
			    )
			)
		displayFolder: Comptabilité
		lineageTag: 3abc58fe-83f5-4e52-9604-64069795112d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM % Résultat' = ```
			
			VAR Revenus_Courant = [Résultat Opérationnel]
			VAR Revenus_Mois_Prec = 
			    CALCULATE(
			        [Résultat Opérationnel],
			        DATEADD('Dim_Date'[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(Revenus_Courant - Revenus_Mois_Prec, Revenus_Mois_Prec, 0)
			```
		displayFolder: Comptabilité
		lineageTag: a333e10b-3b09-45cc-9539-0b9949059adb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Résultat MoM % Text' = ```
			
			VAR _MoM = [MoM % Résultat]
			VAR _Result =
			    SWITCH(
			        TRUE(),
			        ISBLANK(_MoM), "",
			        _MoM < 0, "▼ " & FORMAT(_MoM, "0.0%"), 
			        _MoM >= 0, "▲ " & FORMAT(_MoM, "0.0%")
			    )
			RETURN
			    _Result
			```
		displayFolder: Comptabilité
		lineageTag: 0da3abdc-0f11-46a6-8191-6555450ebaa5

	measure 'Résultat Avg Mo' =
			
			FORMAT(
			    AVERAGEX(
			        ADDCOLUMNS(
			            VALUES('Dim_Date'[Mois]),
			            "Résultat Opérationnel", [Résultat Opérationnel]
			        ),
			        [Résultat Opérationnel]
			    ),
			    "€#,##0,.0K" & " avg/mo"
			)
		displayFolder: Comptabilité
		lineageTag: 19b90703-9514-4d60-9bb6-b8aa597badcb

	measure EBITDA =
			
			CALCULATE(
			    [Soldes],
			    FILTER(
			        'Dim_Ledger Accounts',
			        LEFT('Dim_Ledger Accounts'[number], 2) IN {
			            "70", "71", "72", "74", "75",
			            "60", "61", "62", "63", "64", "65"
			        }
			    )
			)
		displayFolder: Comptabilité
		lineageTag: 2842ac58-b260-41f1-8689-0a36cabcf6a7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM % EBITDA' = ```
			
			VAR EFN_Courant = [EBITDA]
			VAR EFN_Mois_Prec = 
			    CALCULATE(
			        [EBITDA],
			        DATEADD('Dim_Date'[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(EFN_Courant - EFN_Mois_Prec, EFN_Mois_Prec, 0)
			```
		displayFolder: Comptabilité
		lineageTag: 08fc66af-cc1d-4b20-bb4e-766a5ea1ccb3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'EBITDA MoM % Text' = ```
			
			VAR _MoM = [MoM % EBITDA]
			VAR _Result =
			    SWITCH(
			        TRUE(),
			        ISBLANK(_MoM), "",
			        _MoM < 0, "▼ " & FORMAT(_MoM, "0.0%"), 
			        _MoM >= 0, "▲ " & FORMAT(_MoM, "0.0%")
			    )
			RETURN
			    _Result
			```
		displayFolder: Comptabilité
		lineageTag: 758eb47a-3301-4e98-bbc1-08d484132888

	measure 'EBITDA Avg Mo' =
			
			FORMAT(
			    AVERAGEX(
			        ADDCOLUMNS(
			            VALUES('Dim_Date'[Mois]),
			            "EBITDA", [EBITDA]
			        ),
			        [EBITDA]
			    ),
			    "€#,##0,.0K" & " avg/mo"
			)
		displayFolder: Comptabilité
		lineageTag: 71a562f2-008e-4dfa-bcef-2ed3458b6063

	measure Montant_Total_Achats = SUM('Supplier invoices'[amount])
		displayFolder: Achats
		lineageTag: a2fd9104-2d19-4c55-813f-5e2bfc6c037b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fournisseurs Actifs' =
			
			CALCULATE(
			    DISTINCTCOUNT('Supplier invoices'[supplier_id]),
			    NOT ISBLANK('Supplier invoices'[amount])
			)
		formatString: #,0
		displayFolder: Achats
		lineageTag: 0a9e0e08-bdb0-4692-a84c-daad5b3a38ab

	measure 'Factures Impayées' =
			
			CALCULATE(
			    SUM('Supplier invoices'[amount]),
			    'Supplier invoices'[payment_status] IN {"to_be_paid", "to_be_processed"}
			)
		displayFolder: Achats
		lineageTag: 22c38d61-94bf-4207-a48a-f0efb8701a33

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Achats' = SUM('Supplier invoices'[currency_amount_before_tax])
		displayFolder: Achats
		lineageTag: bceb22b4-bbdb-4197-8a89-bbb8cd2b4c58

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Achats MoM % Text' = ```
			
			VAR _MoM = [MoM % Achats]
			VAR _Result =
			    SWITCH(
			        TRUE(),
			        ISBLANK(_MoM), "",
			        _MoM < 0, "▼ " & FORMAT(_MoM, "0.0%"), 
			        _MoM >= 0, "▲ " & FORMAT(_MoM, "0.0%")
			    )
			RETURN
			    _Result
			```
		displayFolder: Achats
		lineageTag: 56049e6c-54a1-4f39-980b-85d3909ce3c2

	measure 'MoM % Achats' =
			
			VAR Achats_Courant = [Total Achats]
			VAR Achats_Mois_Prec =
			    CALCULATE(
			        [Total Achats],
			        DATEADD('Dim_Date'[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(Achats_Courant - Achats_Mois_Prec, Achats_Mois_Prec, 0)
		displayFolder: Achats
		lineageTag: f945005a-1d3d-4bfa-b9bd-4a17729ce3a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Achats Avg Mo' = ```
			
			VAR MoyenneAchats = 
			    AVERAGEX(
			        ADDCOLUMNS(
			            VALUES('Dim_Date'[Mois]),
			            "Achats", [Total Achats]
			        ),
			        [Achats]
			    )
			RETURN
			    FORMAT(MoyenneAchats / 1000000, "€#,##0.00") & "M avg/mo"
			```
		displayFolder: Achats
		lineageTag: db5d5518-324c-461b-80bb-e9118a77d85e

	measure 'Factures Impayées Avg Mo' =
			
			VAR MoyenneImpayees =
			    AVERAGEX(
			        ADDCOLUMNS(
			            VALUES('Dim_Date'[Mois]),
			            "Impayees", [Factures Impayées]
			        ),
			        [Impayees]
			    )
			RETURN
			    FORMAT(MoyenneImpayees / 1000000, "€#,##0.00") & "M avg/mo"
		displayFolder: Achats
		lineageTag: eb43bb64-df87-4aaa-839f-eeb094276750

	measure 'Factures Impayées MoM % Text' = ```
			
			VAR _MoM = [MoM % Factures Impayées]
			VAR _Result =
			    SWITCH(
			        TRUE(),
			        ISBLANK(_MoM), "",
			        _MoM < 0, "▼ " & FORMAT(_MoM, "0.0%"), 
			        _MoM >= 0, "▲ " & FORMAT(_MoM, "0.0%")
			    )
			RETURN
			    _Result
			```
		displayFolder: Achats
		lineageTag: 91d463f0-1dca-4cc7-8af4-34b69ade72fb

	measure 'Fournisseurs Avg Mo' =
			
			VAR MoyenneFournisseurs =
			    AVERAGEX(
			        ADDCOLUMNS(
			            VALUES('Dim_Date'[Mois]),
			            "NbFournisseurs", [Fournisseurs Actifs]
			        ),
			        [NbFournisseurs]
			    )
			RETURN
			FORMAT(MoyenneFournisseurs, "#,##0") & " avg/mo"
		displayFolder: Achats
		lineageTag: 97514d74-7f03-43a4-abfb-cf534d7bf16f

	measure 'EncoursFourn MoM % Text' = ```
			
			VAR _MoM = [MoM % EncoursFourn]
			VAR _Result =
			    SWITCH(
			        TRUE(),
			        ISBLANK(_MoM), "",
			        _MoM < 0, "▼ " & FORMAT(_MoM, "0.0%"), 
			        _MoM >= 0, "▲ " & FORMAT(_MoM, "0.0%")
			    )
			RETURN
			    _Result
			```
		displayFolder: Achats\EncoursFournisseurs
		lineageTag: 8c05737c-99fd-4748-ae23-ed58c92693df

	measure 'MoM % Factures Impayées' =
			
			VAR Impayees_Courant = [Factures Impayées]
			VAR Impayees_Mois_Prec =
			    CALCULATE(
			        [Factures Impayées],
			        DATEADD('Dim_Date'[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(Impayees_Courant - Impayees_Mois_Prec, Impayees_Mois_Prec, 0)
		displayFolder: Achats
		lineageTag: 5f6eeba7-1b47-4518-b295-0677d9890417

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM % Fournisseurs' =
			
			VAR Fournisseurs_Courant = [Fournisseurs Actifs]
			VAR Fournisseurs_Mois_Prec =
			    CALCULATE(
			        [Fournisseurs Actifs],
			        DATEADD('Dim_Date'[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(Fournisseurs_Courant - Fournisseurs_Mois_Prec, Fournisseurs_Mois_Prec, 0)
		displayFolder: Achats
		lineageTag: 5e1d3466-2501-4a5e-9abd-bb361f539a00

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM % tresor' = ```
			
			VAR tresor_Courant = [Trésorerie]
			VAR tresor_Mois_Prec = 
			    CALCULATE(
			        [Trésorerie],
			        DATEADD('Dim_Date'[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(tresor_Courant - tresor_Mois_Prec, tresor_Mois_Prec, 0)
			```
		displayFolder: Comptabilité\tresorerie
		lineageTag: 950e6aaf-4ab7-44fe-a82a-1a818d09337a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'tresor MoM % Text' = ```
			
			VAR _MoM = [MoM % tresor]
			VAR _Result =
			    SWITCH(
			        TRUE(),
			        ISBLANK(_MoM), "",
			        _MoM < 0, "▼ " & FORMAT(_MoM, "0.0%"), 
			        _MoM >= 0, "▲ " & FORMAT(_MoM, "0.0%")
			    )
			RETURN
			    _Result
			```
		displayFolder: Comptabilité\tresorerie
		lineageTag: 33108c8b-067d-40fb-9258-cb2c3ec9f4eb

	measure 'tresor Avg Mo' =
			
			FORMAT(
			    AVERAGEX(
			        ADDCOLUMNS(
			            VALUES('Dim_Date'[Mois]),
			            "Endettement Financier Net", [Trésorerie]
			        ),
			        [Endettement Financier Net]
			    ),
			    "€#,##0,.0K" & " avg/mo"
			)
		displayFolder: Comptabilité\tresorerie
		lineageTag: 01b2f8a1-2082-43ec-aa13-b3f8726532ea

	measure 'Encours Clients' =
			
			CALCULATE(
			    [Soldes Customer Invoices],
			    FILTER(
			        'Customer invoices',
			        'Customer invoices'[status] IN {
			            "late","upcoming","partially_cancelled"
			        }
			    )
			)
		displayFolder: Ventes\Client
		lineageTag: 7e4cae93-9365-435c-a8ee-7408a2b5bf67

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Client Avg Mo' =
			
			FORMAT(
			    AVERAGEX(
			        ADDCOLUMNS(
			            VALUES('Dim_Date'[Mois]),
			            "Capitaux Propres", [Encours Clients]
			        ),
			        [Capitaux Propres]
			    ),
			    "€#,##0,.0K" & " avg/mo"
			)
		displayFolder: Ventes\Client
		lineageTag: c4bfc80d-7a77-4600-98cf-6b260d5288ee

	measure 'MoM % Client' = ```
			
			VAR Client_Courant = [Encours Clients]
			VAR Client_Mois_Prec = 
			    CALCULATE(
			        [Encours Clients],
			        DATEADD('Dim_Date'[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(Client_Courant - Client_Mois_Prec, Client_Mois_Prec, 0)
			```
		displayFolder: Ventes\Client
		lineageTag: 52df7f24-0fd1-47c4-9275-4dc7c1bc9b2e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Client MoM % Text' = ```
			
			VAR _MoM = [MoM % Client]
			VAR _Result =
			    SWITCH(
			        TRUE(),
			        ISBLANK(_MoM), "",
			        _MoM < 0, "▼ " & FORMAT(_MoM, "0.0%"), 
			        _MoM >= 0, "▲ " & FORMAT(_MoM, "0.0%")
			    )
			RETURN
			    _Result
			```
		displayFolder: Ventes\Client
		lineageTag: 3913ea0a-9509-48c2-8674-740959603f1e

	measure 'Encours Fournisseurs' =
			
			CALCULATE(
			    [Soldes Supplier Invoices],
			    FILTER(
			        'Supplier invoices',
			        'Supplier invoices'[payment_status] IN {
			            "to_be_paid","to_be_processed"
			        }
			    )
			)
		displayFolder: Achats\EncoursFournisseurs
		lineageTag: 4dfe525d-7cfd-4208-99a2-99d49a40467c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM % EncoursFourn' =
			
			VAR Achats_Courant = [Encours Fournisseurs]
			VAR Achats_Mois_Prec =
			    CALCULATE(
			        [Encours Fournisseurs],
			        DATEADD('Dim_Date'[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(Achats_Courant - Achats_Mois_Prec, Achats_Mois_Prec, 0)
		displayFolder: Achats\EncoursFournisseurs
		lineageTag: 38fa4aa0-0159-4069-9ad7-4ccd06d23397

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'EncoursFourn Avg Mo' =
			
			VAR MoyenneFournisseurs =
			    AVERAGEX(
			        ADDCOLUMNS(
			            VALUES('Dim_Date'[Mois]),
			            "Encours Fournisseurs", [Encours Fournisseurs]
			        ),
			        [Encours Fournisseurs]
			    )
			RETURN
			FORMAT(MoyenneFournisseurs, "#,##0") & " avg/mo"
		displayFolder: Achats\EncoursFournisseurs
		lineageTag: 4436830c-e18f-4a4e-8f93-81915bda6af9

	measure 'Soldes Customer Invoices' = SUM('Customer invoices'[amount])
		displayFolder: Ventes\Client
		lineageTag: 8d9970c6-3501-4aaf-bd77-4b767f2e4542

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Trésorerie Nette' = [Trésorerie] + [Encours Clients] - [Encours Fournisseurs]
		displayFolder: Comptabilité\tresorerie
		lineageTag: 5cec1534-a323-4491-93b0-b936fae187ae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Ventes n-1' =
			
			CALCULATE(
			    [Soldes],
			    SAMEPERIODLASTYEAR(Dim_Date[Date]),
			    FILTER(
			        'Dim_Ledger Accounts',
			        'Dim_Ledger Accounts'[IsVente] = 1
			    )
			)
		displayFolder: Ventes
		lineageTag: e46d37b1-f27d-4075-8db3-1f2e4a3e432c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Achats n-1' = CALCULATE(SUM('Supplier invoices'[currency_amount_before_tax]),SAMEPERIODLASTYEAR(Dim_Date[Date]))
		displayFolder: Achats
		lineageTag: 24849206-2f38-4361-a5c3-a35e0b649c31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Exercice sélectionné' = ```
			
			VAR SelectedCompany = SELECTEDVALUE('Dim_Companies'[id])
			VAR DateCourante = SELECTEDVALUE('Dim_Date'[Date])
			
			VAR StartDate =
			    CALCULATE(
			        MAX('fiscal_years'[start_date]),
			        FILTER(
			            ALL('fiscal_years'),
			            'fiscal_years'[company_id] = SelectedCompany &&
			            DateCourante >= 'fiscal_years'[start_date] &&
			            DateCourante <= 'fiscal_years'[end_date]
			        )
			    )
			
			RETURN
			    IF(
			        NOT ISBLANK(StartDate),
			        "Exo" & RIGHT(YEAR(StartDate), 2),
			        BLANK()
			    )
			
			```
		lineageTag: 899864f4-679f-4f2d-ac56-7eacdc33ef52

	measure 'Période visible' = ```
			
			VAR SelectedCompany = SELECTEDVALUE('Dim_Companies'[id])
			VAR DateCourante = SELECTEDVALUE('Dim_Date'[Date])
			
			RETURN
			    CALCULATE(
			        COUNTROWS('fiscal_years'),
			        FILTER(
			            ALL('fiscal_years'),
			            'fiscal_years'[company_id] = SelectedCompany &&
			            DateCourante >= 'fiscal_years'[start_date] &&
			            DateCourante <= 'fiscal_years'[end_date]
			        )
			    ) > 0
			
			```
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3be47409-2155-456e-817e-02af9a01d79a

	measure 'StartExercice sélectionné' = ```
			
			VAR SelectedCompany = SELECTEDVALUE('Dim_Companies'[id])
			
			RETURN
			    CALCULATE(
			        MIN('fiscal_years'[start_date]),
			        FILTER(
			            ALL('fiscal_years'),
			            'fiscal_years'[company_id] = SelectedCompany
			        )
			    )
			
			```
		formatString: General Date
		lineageTag: 24bc4d23-feb2-48a7-876f-8a1dcac3e694

	measure 'EndExercice sélectionné' = ```
			
			VAR SelectedCompany = SELECTEDVALUE('Dim_Companies'[id])
			
			RETURN
			    CALCULATE(
			        MAX('fiscal_years'[end_date]),
			        FILTER(
			            ALL('fiscal_years'),
			            'fiscal_years'[company_id] = SelectedCompany
			        )
			    )
			
			```
		formatString: General Date
		lineageTag: c8980c3f-979f-4680-8a8b-e5f4265ad99a

	measure 'Exercice (mesure)' = ```
			
			VAR SelectedCompany = SELECTEDVALUE('Dim_Companies'[id])
			VAR CurrentDate = SELECTEDVALUE('Dim_Date'[Date])
			
			VAR FiscalStart =
			    CALCULATE(
			        MAX('fiscal_years'[start_date]),
			        FILTER(
			            ALL('fiscal_years'),
			            'fiscal_years'[company_id] = SelectedCompany &&
			            CurrentDate >= 'fiscal_years'[start_date] &&
			            CurrentDate <= 'fiscal_years'[end_date]
			        )
			    )
			
			RETURN
			    IF(
			        NOT ISBLANK(FiscalStart),
			        "Exo" & RIGHT(YEAR(FiscalStart), 2)
			    )
			
			```
		lineageTag: 5c159508-15a9-4b3d-aa03-dfa063864a9e

	measure 'Dernière MAJ' =
			"MAJ : "&
			FORMAT(
			    MAX('Supplier invoices'[updated_at]),
			    "dd/mm/yy HH:mm"
			)
		lineageTag: b8e113e1-7243-41f2-b3b4-765dbd6adbf9

	measure 'Délai Moyen Paiement' = ```
			
			AVERAGEX(
			    FILTER(
			        'Customer invoices',
			        NOT(ISBLANK(Factures[Date_Paiement])) && 
			        NOT(ISBLANK(Factures[Date_Echeance]))
			    ),
			    DATEDIFF(Factures[Date_Echeance], Factures[Date_Paiement], DAY)
			)
			```
		displayFolder: Achats
		lineageTag: 7a6e9ed8-22e8-4008-9d81-8a4494302141

	measure 'Solde 7' = ABS(CALCULATE([Solde], 'Dim_Ledger Accounts'[IsVente] = 1))
		displayFolder: Comptabilité
		lineageTag: 3c00622f-9e30-465a-96c0-463b63cb1d5f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Solde 6' = ABS(CALCULATE([Solde], 'Dim_Ledger Accounts'[IsAchat] = 1))
		displayFolder: Comptabilité
		lineageTag: e56a4ab8-563d-4eb8-9559-5fb3491bf8e2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CA_12M_Glissants =
			
			VAR MaxDate = CALCULATE(
			    MAX('Fact_GL'[date]),
			    REMOVEFILTERS('Dim_Date')  -- Pour prendre la date réelle la plus récente
			)
			VAR DateMin = EDATE(MaxDate, -11)
			
			RETURN
			CALCULATE(
			    [Solde 7],
			    FILTER(
			        ALL('Dim_Date'),
			        'Dim_Date'[Date] >= DateMin &&
			        'Dim_Date'[Date] <= MaxDate
			    )
			)
		displayFolder: Comptabilité
		lineageTag: 4b9a44c9-62cd-4a66-8ece-819a594d2f4a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Afficher_12M_Glissants =
			
			VAR MaxDate = MAX(Dim_Date[Date])
			VAR Date12MoisAvant = EDATE(MaxDate, -11)
			RETURN
			IF(
			    Dim_Date[Date] >= Date12MoisAvant && Dim_Date[Date] <= MaxDate,
			    1,
			    0
			)
		displayFolder: Comptabilité
		lineageTag: 6b5f0bbe-c2dc-41fe-9136-e44e6780792b

	measure PreviousYear = MAX(Dim_Date[Année])-1
		formatString: 0
		displayFolder: Titres Dynamique\Year Legend
		lineageTag: 437d85bd-a360-498e-a139-e962b3ac0780

	measure ThisYear = MAX(Dim_Date[Année])
		formatString: 0
		displayFolder: Titres Dynamique\Year Legend
		lineageTag: b8fb9b07-8d1f-4fbb-95ae-44eb4f217787

	measure CA/Charge = "CA/Charge - "&[ThisYear]
		displayFolder: Titres Dynamique\Titres
		lineageTag: dd725b0a-b101-47ca-874a-3ca7bd727894

	measure 'Top 5 Clients Retard' = "Top 5 Clients en Retard de Paiement - "&[ThisYear]
		displayFolder: Titres Dynamique\Titres
		lineageTag: 166fded6-baf2-48a9-9693-af56d7eda1bc

	measure 'Balance Agée Clients' = "Balance Agée Clients - "&[ThisYear]
		displayFolder: Titres Dynamique\Titres
		lineageTag: f4b0f50b-6207-4d07-8504-48c0494f5b07

	measure 'Min Value' = MIN('Mesures'[Résultat Opérationnel])
		displayFolder: Comptabilité
		lineageTag: a5faabcb-4b84-4830-bd91-eab8d3233715

	measure 'Debug CurrentResult' =
			
			CALCULATE (
			    ROUND ( [Résultat Opérationnel], 2 ),
			    FILTER ( ALL ( 'Dim_Date'[Mois] ), 'Dim_Date'[Mois] = "January" )
			)
		lineageTag: c68d930e-af08-4d77-85aa-2c26aa389e77

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Test Min Value' =
			
			VAR MinResult = MINX(ALL('Dim_Date'[Mois]), ROUND([Résultat Opérationnel], 2))
			RETURN MinResult
		lineageTag: 153afcbe-42c4-4948-922c-7910b58148b9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Test Max Value' =
			
			VAR MaxResult = MAXX(ALL('Dim_Date'[Mois]), ROUND([Résultat Opérationnel], 2))
			RETURN MaxResult
		lineageTag: b7b198fa-6485-4a27-bad9-38ca69696b70

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CA = ```
			
			
			    [Solde 7]
			```
		displayFolder: Comptabilité
		lineageTag: 66d3e747-9988-434f-a986-ceae5992249b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Charges = ```
			
			    [Solde 6]
			```
		displayFolder: Comptabilité
		lineageTag: dac96eec-09c4-43d5-96f7-5f72caa71550

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Resultat Cumulées(M)' =
			
			CALCULATE (
			    [Soldes],
			    FILTER (
			        ALLSELECTED ( 'Dim_Date' ),
			        'Dim_Date'[Date] <= MAX ( 'Dim_Date'[Date] )
			            && YEAR ( 'Dim_Date'[Date] ) = YEAR ( MAX ( 'Dim_Date'[Date] ) )
			    ),
			    FILTER (
			        'Dim_Ledger Accounts',
			        LEFT ( 'Dim_Ledger Accounts'[Compte], 1 ) IN { "6", "7" }
			    )
			)
		displayFolder: Comptabilité
		lineageTag: b562f6cf-516c-4d64-9e10-80ae6c0ec216

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Color Max Min TN' = ```
			
			VAR CurrentValue = [Trésorerie Nette]
			VAR SelectedYear = SELECTEDVALUE('Dim_Date'[Année])
			VAR MaxValue =
			    SWITCH(
			        SelectedYear,
			        2025, 428256.32,
			        2024, -6057.94,
			        2023, 3170.60,
			        428256.32  // Default fallback for 2025
			    )
			VAR MinValue =
			    SWITCH(
			        SelectedYear,
			        2025, -93137.52,
			        2024, -100705.42,
			        2023, -47528.13,
			        -93137.52  // Default fallback for 2025
			    )
			RETURN 
			    IF(
			        ABS(CurrentValue - MaxValue) < 1 || ABS(CurrentValue - MinValue) < 1,
			        "#9fbec3",  // Light blue for both max and min
			        "#487888"   // Default dark blue for others
			    )
			```
		lineageTag: dcae1c03-977a-4047-91de-67273e33b05c

	measure 'Color Max Min EC' = ```
			
			VAR CurrentValue = [Encours Clients]
			VAR SelectedYear = SELECTEDVALUE('Dim_Date'[Année])
			VAR MaxValue =
			    SWITCH(
			        SelectedYear,
			        2025, 569905.04,
			        2024, 10500.00,
			        2023, 19998.00,
			        569905.04  // Default fallback for 2025
			    )
			VAR MinValue =
			    SWITCH(
			        SelectedYear,
			        2025, 4000.00,
			        2024, 1063.37,
			        2023, 809.75,
			        4000.00  // Default fallback for 2025
			    )
			RETURN 
			    IF(
			        ABS(CurrentValue - MaxValue) < 1 || ABS(CurrentValue - MinValue) < 1,
			        "#9fbec3",  // Light blue for both max and min
			        "#487888"   // Default dark blue for others
			    )
			```
		lineageTag: 08be9f6e-d7ce-4c5c-a01d-c2673371ec4a

	measure 'Color Max Min EF' = ```
			
			VAR CurrentValue = [Encours Fournisseurs]
			VAR SelectedYear = SELECTEDVALUE('Dim_Date'[Année])
			VAR MaxValue =
			    SWITCH(
			        SelectedYear,
			        2025, 141648.72,
			        2024, 101880.46,
			        2023, 47528.13,
			        141648.72  // Default fallback for 2025
			    )
			VAR MinValue =
			    SWITCH(
			        SelectedYear,
			        2025, 46149.37,
			        2024, 13914.98,
			        2023, 2722.58,
			        46149.37  // Default fallback for 2025
			    )
			RETURN 
			    IF(
			        ABS(CurrentValue - MaxValue) < 1 || ABS(CurrentValue - MinValue) < 1,
			        "#9fbec3",  // Light blue for both max and min
			        "#487888"   // Default dark blue for others
			    )
			
			```
		lineageTag: c5466fe4-24b1-4ff6-b76e-459d3c0c1018

	measure 'Color Max Min RO' = ```
			
			VAR CurrentValue = [Résultat Opérationnel]
			VAR SelectedYear = SELECTEDVALUE('Dim_Date'[Année])
			VAR MaxValue =
			    SWITCH(
			        SelectedYear,
			        2025, 257964.19,
			        2024, 277032.00,
			        2023, 269947.91,
			        257964.19  // Default fallback for 2025
			    )
			VAR MinValue =
			    SWITCH(
			        SelectedYear,
			        2025, -470678.63,
			        2024, -211342.82,
			        2023, -74448.32,
			        -470678.63  // Default fallback for 2025
			    )
			RETURN 
			    IF(
			        ABS(CurrentValue - MaxValue) < 1 || ABS(CurrentValue - MinValue) < 1,
			        "#9fbec3",  // Light blue for both max and min
			        "#487888"   // Default dark blue for others
			    )
			
			```
		lineageTag: 6491b6c3-53f9-4853-ba5f-a18ed560c6fe

	measure 'Color Max Min TV' = ```
			
			VAR CurrentValue = [Total Ventes]
			VAR SelectedYear = SELECTEDVALUE('Dim_Date'[Année])
			VAR MaxValue =
			    SWITCH(
			        SelectedYear,
			        2025, 477981,
			        2024, 454469,
			        2023, 545951,
			        477981  // Default fallback for 2025
			    )
			VAR MinValue =
			    SWITCH(
			        SelectedYear,
			        2025, 176733,
			        2024, 80522,
			        2023, 53240,
			        176733  // Default fallback for 2025
			    )
			RETURN 
			    IF(
			        ABS(CurrentValue - MaxValue) < 1 || ABS(CurrentValue - MinValue) < 1,
			        "#9fbec3",  // Light blue for both max and min
			        "#487888"   // Default dark blue for others
			    )
			```
		lineageTag: f6e3a632-4547-4d6e-ab91-93cb6ca11b04

	measure 'CA HT Display' = ```
			
			FORMAT([Total Ventes], "#,0,,") & "K €"
			
			```
		lineageTag: 4ce3ced3-8179-4293-a565-b4ecdbe629fa

	column Column
		isHidden
		formatString: 0
		lineageTag: a6408794-3fc3-4f2c-a733-d02e4a1aa9bd
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition Mesures = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 90d44fa8782b49559d4a8e637d46b27d

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

